language: python
python:
#  - "2.5"
  - "2.6"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt
install: pip install -r .travis.requirements.txt
# command to run tests, e.g. python setup.py test
script:  python test.py

notifications:
  email:
    recipients:
        - kormoc@gmail.com
    on_success: change
    on_failure: always
